### ISSUE TITLE
Add ATMega4809 Device

### ISSUE THREAD

**Issue by maxgerhardt** [Florin-Popescu/avarice#3]
I've seen the ATMega4808 already being added and [per datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/ATmega4808-4809-Data-Sheet-DS40002173A.pdf) it is like a ATMega4808 but with more pins and one UART. 

I can't propose the changes myself because I can't get the program running right now to verify it, see other issue :(.

**Comment by Florin-Popescu** [comment]
Closing this since it's getting fairly old and I don't have a 4809 to test support for it. Please let me know if you get things working and need further assistance.
