### ISSUE TITLE
Upstream changes

### ISSUE THREAD

**Issue by maxgerhardt** [Florin-Popescu/avarice#9]
I love your work on avarice and UPDI and especially building on Windows. Avarice now also has a Github repo at https://github.com/avrdudes/avarice. It would be really nice if we could upstream all these improvements and fixes to mainline, to have one version, available for all operating systems.

**Comment by Florin-Popescu** [comment]
Hi Maximilian,

Thanks, it's good to hear that it's been added to GitHub, this will surely help bring more people in.

I'll try to submit a pull request some time in the next days.

**Comment by Florin-Popescu** [comment]
PR submitted.
